stages:
    - test
    - deploy

test_job:
    stage: test
    script:
        - /usr/bin/hugo check

deploy_job:
    stage: deploy
    script:
        - /usr/bin/sudo -u www-data -H /usr/bin/hugo -d ~www-data/nothing.to/prod/
    only:
        - master
